import "@/styles/globals.css";
import { Coupon } from "@/components/Coupon";
import { Header } from "@/components/Header";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Header />
        <Coupon />
        <section className="flex items-center justify-center py-10 px-[40px]">
          {children}
        </section>
      </body>
    </html>
  );
}
